# Generated by Django 5.1.3 on 2024-11-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='tarefa',
            new_name='tarefas',
        ),
    ]
