# Generated by Django 5.1.3 on 2024-11-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_tarefa_tarefa_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tarefas',
            field=models.CharField(max_length=200),
        ),
    ]
