# Generated by Django 5.1.3 on 2024-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_created_at_tarefa_done_tarefa_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='done',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5),
        ),
    ]
