# Generated by Django 5.1.3 on 2024-11-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_tarefa_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tarefa',
            new_name='task',
        ),
    ]
